-- MySQL Script generated by MySQL Workbench
-- Mon Mar 20 14:34:30 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema PathFinder_BD
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema PathFinder_BD
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `PathFinder_BD` ;
USE `PathFinder_BD` ;

-- -----------------------------------------------------
-- Table `PathFinder_BD`.`Utilisateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PathFinder_BD`.`Utilisateur` (
  `id_Utilisateur` INT NOT NULL AUTO_INCREMENT,
  `nom_Utilisateur` VARCHAR(45) NULL,
  `prenom_Utilisateur` VARCHAR(45) NULL,
  `email_Utilisateur` VARCHAR(45) NULL,
  `mpd_utilisateur` VARCHAR(45) NULL,
  `date_creation_utilisateur` DATE NULL,
  `num_tel_Utilisateur` INT NULL,
  `localisation_Utilisateur` VARCHAR(45) NULL,
  PRIMARY KEY (`id_Utilisateur`),
  UNIQUE INDEX `idUtilisateur_UNIQUE` (`id_Utilisateur` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PathFinder_BD`.`Payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PathFinder_BD`.`Payment` (
  `id_Payment` INT NOT NULL AUTO_INCREMENT,
  `montant` DOUBLE NULL,
  `mode_payment` VARCHAR(45) NULL,
  PRIMARY KEY (`id_Payment`),
  UNIQUE INDEX `id_Payment_UNIQUE` (`id_Payment` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PathFinder_BD`.`Centre_de_formation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PathFinder_BD`.`Centre_de_formation` (
  `id_Centre` INT NOT NULL AUTO_INCREMENT,
  `nom_Centre` VARCHAR(45) NULL,
  `adresse_centre` VARCHAR(45) NULL,
  `region_Centre` VARCHAR(45) NULL,
  `ville_centre` VARCHAR(45) NULL,
  `num_tel_Centre` INT NULL,
  `email_centre` VARCHAR(45) NULL,
  `site_web_centre` VARCHAR(45) NULL,
  `description_centre` VARCHAR(100) NULL,
  `Utilisateur_id_Utilisateur` INT NOT NULL,
  `Payment_id_Payment` INT NOT NULL,
  PRIMARY KEY (`id_Centre`, `Payment_id_Payment`),
  INDEX `fk_Centre_de_formation_Utilisateur1_idx` (`Utilisateur_id_Utilisateur` ASC) VISIBLE,
  INDEX `fk_Centre_de_formation_Payment1_idx` (`Payment_id_Payment` ASC) VISIBLE,
  CONSTRAINT `fk_Centre_de_formation_Utilisateur1`
    FOREIGN KEY (`Utilisateur_id_Utilisateur`)
    REFERENCES `PathFinder_BD`.`Utilisateur` (`id_Utilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Centre_de_formation_Payment1`
    FOREIGN KEY (`Payment_id_Payment`)
    REFERENCES `PathFinder_BD`.`Payment` (`id_Payment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PathFinder_BD`.`Categorie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PathFinder_BD`.`Categorie` (
  `id_Categorie` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom_Categorie` VARCHAR(45) NULL,
  `description_Categorie` VARCHAR(100) NULL,
  PRIMARY KEY (`id_Categorie`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PathFinder_BD`.`Formation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PathFinder_BD`.`Formation` (
  `id_Formation` INT NOT NULL AUTO_INCREMENT,
  `nom_Formation` VARCHAR(45) NULL,
  `description_Formation` VARCHAR(100) NULL,
  `date_debut` DATE NULL,
  `date_fin` DATE NULL,
  `prix_formation` DOUBLE NULL,
  `duree_Formation` DATETIME NULL,
  `Categorie_id_Categorie` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_Formation`),
  INDEX `fk_Formation_Categorie1_idx` (`Categorie_id_Categorie` ASC) VISIBLE,
  CONSTRAINT `fk_Formation_Categorie1`
    FOREIGN KEY (`Categorie_id_Categorie`)
    REFERENCES `PathFinder_BD`.`Categorie` (`id_Categorie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PathFinder_BD`.`Note`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PathFinder_BD`.`Note` (
  `id_Note` INT NOT NULL AUTO_INCREMENT,
  `nombre_etoiles` INT NULL,
  `Utilisateur_id_Utilisateur` INT NOT NULL,
  `Centre_de_formation_id_Centre` INT NOT NULL,
  `Formation_id_Formation` INT NOT NULL,
  PRIMARY KEY (`id_Note`),
  UNIQUE INDEX `id_Note_UNIQUE` (`id_Note` ASC) VISIBLE,
  INDEX `fk_Note_Utilisateur_idx` (`Utilisateur_id_Utilisateur` ASC) VISIBLE,
  INDEX `fk_Note_Centre_de_formation1_idx` (`Centre_de_formation_id_Centre` ASC) VISIBLE,
  INDEX `fk_Note_Formation1_idx` (`Formation_id_Formation` ASC) VISIBLE,
  CONSTRAINT `fk_Note_Utilisateur`
    FOREIGN KEY (`Utilisateur_id_Utilisateur`)
    REFERENCES `PathFinder_BD`.`Utilisateur` (`id_Utilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Note_Centre_de_formation1`
    FOREIGN KEY (`Centre_de_formation_id_Centre`)
    REFERENCES `PathFinder_BD`.`Centre_de_formation` (`id_Centre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Note_Formation1`
    FOREIGN KEY (`Formation_id_Formation`)
    REFERENCES `PathFinder_BD`.`Formation` (`id_Formation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PathFinder_BD`.`Commentaire`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PathFinder_BD`.`Commentaire` (
  `id_Commentaire` INT NOT NULL AUTO_INCREMENT,
  `text` VARCHAR(100) NULL,
  `date_creation_comm` DATE NULL,
  `Utilisateur_id_Utilisateur` INT NOT NULL,
  `Centre_de_formation_id_Centre` INT NOT NULL,
  `Formation_id_Formation` INT NOT NULL,
  PRIMARY KEY (`id_Commentaire`),
  UNIQUE INDEX `id_Commentaire_UNIQUE` (`id_Commentaire` ASC) VISIBLE,
  INDEX `fk_Commentaire_Utilisateur1_idx` (`Utilisateur_id_Utilisateur` ASC) VISIBLE,
  INDEX `fk_Commentaire_Centre_de_formation1_idx` (`Centre_de_formation_id_Centre` ASC) VISIBLE,
  INDEX `fk_Commentaire_Formation1_idx` (`Formation_id_Formation` ASC) VISIBLE,
  CONSTRAINT `fk_Commentaire_Utilisateur1`
    FOREIGN KEY (`Utilisateur_id_Utilisateur`)
    REFERENCES `PathFinder_BD`.`Utilisateur` (`id_Utilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Commentaire_Centre_de_formation1`
    FOREIGN KEY (`Centre_de_formation_id_Centre`)
    REFERENCES `PathFinder_BD`.`Centre_de_formation` (`id_Centre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Commentaire_Formation1`
    FOREIGN KEY (`Formation_id_Formation`)
    REFERENCES `PathFinder_BD`.`Formation` (`id_Formation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PathFinder_BD`.`Reclamation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PathFinder_BD`.`Reclamation` (
  `id_Reclamation` INT NOT NULL AUTO_INCREMENT,
  `texte_Reclamation` VARCHAR(200) NULL,
  `Utilisateur_id_Utilisateur` INT NOT NULL,
  PRIMARY KEY (`id_Reclamation`),
  UNIQUE INDEX `id_Reclamation_UNIQUE` (`id_Reclamation` ASC) VISIBLE,
  INDEX `fk_Reclamation_Utilisateur1_idx` (`Utilisateur_id_Utilisateur` ASC) VISIBLE,
  CONSTRAINT `fk_Reclamation_Utilisateur1`
    FOREIGN KEY (`Utilisateur_id_Utilisateur`)
    REFERENCES `PathFinder_BD`.`Utilisateur` (`id_Utilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PathFinder_BD`.`Centre_de_formation_has_Formation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PathFinder_BD`.`Centre_de_formation_has_Formation` (
  `Formation_id_Formation` INT NOT NULL,
  `Centre_de_formation_id_Centre` INT NOT NULL,
  PRIMARY KEY (`Formation_id_Formation`, `Centre_de_formation_id_Centre`),
  INDEX `fk_Formation_has_Centre_de_formation_Centre_de_formation1_idx` (`Centre_de_formation_id_Centre` ASC) VISIBLE,
  INDEX `fk_Formation_has_Centre_de_formation_Formation1_idx` (`Formation_id_Formation` ASC) VISIBLE,
  CONSTRAINT `fk_Formation_has_Centre_de_formation_Formation1`
    FOREIGN KEY (`Formation_id_Formation`)
    REFERENCES `PathFinder_BD`.`Formation` (`id_Formation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Formation_has_Centre_de_formation_Centre_de_formation1`
    FOREIGN KEY (`Centre_de_formation_id_Centre`)
    REFERENCES `PathFinder_BD`.`Centre_de_formation` (`id_Centre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
